https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index/微信公众平台接口测试
http://www.dooccn.com/php5.4/php5.4代码在线测试/php5.4在线执行
http://caibaojian.com/es6/let.html/ES6文档
http://www.runoob.com/cssref/css-selectors.html/CSS选择器|菜鸟教程
https://www.yiibai.com/mysql/mysql_max_function.html/MySQL教程
http://www.ofmonkey.com/docs/contenttype/Content-type参考
http://v3.bootcss.com/css/#helper-classes/全局CSS样式Bootstrapv3中文文档
https://www.magentonotes.com/tool/layoutit/Bootstrap可视化布局系统
http://fontello.com/Fontello-文件图标
https://packagist.org/compostorphppackage
http://docs.phalapi.net/#/v2.0/PhalApi(π框架)
http://ai.baidu.com/docs#/FaceLogin/top/文档中心--百度AI
http://cdn.code.baidu.com/百度静态资源公共库
https://chajian.baidu.com/developer/extensions/api_index.html/百度浏览器应用开发文档
http://see.sl088.com/wiki/%E5%88%86%E7%B1%BB:Chrome%E6%89%A9%E5%B1%95/分类:Chrome扩展
http://ocr.wdku.net/文字识别
https://www.processon.com/popular/ProcessOn
https://tool.lu/程序员的工具箱
http://sfz.uzuzuz.com/身份证号码生成
https://www.fakenamegenerator.com/GenerateaRandomName
https://szjzz.szga.gov.cn/index/queryHouseCode/深圳居住证平台房屋编码查询
http://www.szjs.gov.cn/bsfw/zdyw_1/zfbz/gxfgs/公租房轮候信息公示-深圳住房和建设局
http://www.szga.gov.cn/JMHD/ZXTSDF/信箱回复«警民互动«深圳市公安局
http://zhixing.court.gov.cn/search/全国法院被执行人信息查询
http://www.szsi.gov.cn/gzfw/dfyjcx/答复意见查询-深圳社会保险基金管理局
https://ipcrs.pbccrc.org.cn/个人信用信息服务平台
http://liuyan.people.com.cn/forum/list?fid=266/地方领导留言板
http://61.142.120.214:9000/web/salestable.jsp?buildingcode=DYW0020600402&projectcode=DYW00206004/楼盘销售表
http://top.baidu.com/buzz?b=1&fr=topindex/实时热点排行榜--百度搜索风云榜
https://weibo.com/?category=1760/微博-随时随地发现新鲜事
http://s.weibo.com/top/summary/微博热搜-微博
http://weixin.sogou.com/搜狗微信搜索
http://news.163.com/rank/新闻排行榜_网易新闻
http://fund.eastmoney.com/f10/jjfl_000693.html/建信现金添利货币A
http://www.soocang.com/搜藏网-中国艺术收藏投资界综合门户网站
http://www.cyzone.cn/创业邦-全维度创业者服务平台
https://codemart.com/码市-互联网软件外包服务平台
https://www.zhipin.com/BOSS直聘-互联网招聘神器！
http://lusongsong.com/卢松松博客
http://blog.knownsec.com/Knownsec_RD_Checklist/index.html/知道创宇研发技能表v3.1
http://www.romjd.com/ROM基地
http://www.phoenixos.com/download_x86/凤凰系统x86版-PhoenixOS
https://bbs.jide.com/forum.php/RemixOS
https://www.deepin.org/深度系统
http://blog.csdn.net/lhf_tiger/article/details/7102753/linux查看系统信息命令(比较全)
https://baijiahao.baidu.com/s?id=1586016551590193087&wfr=spider&for=pc/Linux+Virtualbox虚拟Android7.1环境
http://www.x86android.com/thread-150093-1-1.html/Android-x867.1-r1(Nougat-x86)
http://www.dcloud.io/wap2app.html/wap2app将M站快速转换成App的开发框架-DCloud
http://www.miued.com/蓝色早晨-UED|艺术与设计
https://www.jiawin.com/觉唯设计_用户体验设计分享平台
http://ued.qq.com/腾讯网UED|官方网站
http://www.aliued.cn/阿里巴巴
http://uedc.163.com/网易用户体验设计中心
http://ued.qunar.com/QunarUED
http://jdc.jd.com/JDC|京东设计中心
http://ued.baidu.com/百度用户体验中心
http://hao.uisdc.com/SDC设计师网址导航
https://bbs.csdn.net/CSDN
https://www.52pojie.cn/forum.php?mod=guide&view=newthread/吾爱破解
https://szbbs.sznews.com/forum.php?mod=guide&;view=hot/深圳论坛
https://www.sogou.com/web?ie=utf8&amp;query=%E4%B8%87%E5%B9%B4%E5%8E%86/万年历-搜狗搜索
http://bbs.szhome.com/家在深圳
http://www.google.cn/maps/google
https://ditu.baidu.com/百度
http://map.sogou.com/搜狗
https://ditu.amap.com/高德
https://cn.bing.com/search?q=%E5%85%AC%E5%BC%80%E8%AF%BE/公开课-bing
https://www.sogou.com/web?ie=utf8&amp;query=%E4%B8%87%E5%B9%B4%E5%8E%86/万年历-搜狗搜索
https://www.baidu.com/s?wd=深圳租房/深圳租房
https://www.baidu.com/more/百度产品大全
http://www.sogou.com/docs/more.htm/搜狗产品大全
http://www.so.com/zt/so_products.html/360产品大全
http://sitemap.163.com/网站地图_网易
http://news.sina.com.cn/guide/新浪网站导航_新浪网
